name: Ponder
version: 0.4-alpha-1
authors: [Daniel Stephenson, Callum]
main: preponderous.ponder.Ponder
api-version: 1.13
description: Intended to facilitate the creation and expansion of Minecraft plugins.